import type { Metadata } from "next";
import {  Nunito_Sans, Montserrat, Lusitana } from "next/font/google";
import "./globals.css";
import { AppFooter } from "./ui/app-footer";
import { AppHeader } from "./ui/app-header";


// access these fonts in the 
const nunito = Nunito_Sans({
  variable: "--font-nunito",
  weight: '700',
  subsets: ["latin"],
});

const lusitana = Lusitana({
  variable: "--font-lusitana",
  weight: '400',
  subsets: ["latin"],
});


const montserrat = Montserrat({
  variable: "--font-montserrat",
  weight: '700',
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${nunito.variable} antialiased`}
      >
       <AppHeader></AppHeader> 
        {children}
        <AppFooter></AppFooter>
      </body>
    </html>
  );
}
